# APT Activity Experiment
This notebook contains code to aim to answer the following question: How active are APTs after their first operation?
Advanced APT attack operations will remain several for several years. [APT Cyber-Attack Modeling](https://books.google.nl/books?hl=nl&lr=&id=Shd2EAAAQBAJ&oi=fnd&pg=PA121&dq=apt+cyber+attack+activity&ots=syhFrdDUk7&sig=ejQ0v5LJ12c_SPUZe9f7pt8cmq0#v=onepage&q=apt%20cyber%20attack%20activity&f=false) shows the difference in first detection versus their first operation.

The results are used to choose a weighting function for operations in the actor ranking.

In [49]:
import pandas as pd

df = pd.read_json('ETDA_ATTCK_merge.json')
df = df[['etda_name','etda_first_seen','etda_operation_year']]
df['total_ops'] = df['etda_operation_year'].apply(len)
df.sort_values(by='total_ops')

,etda_name,etda_first_seen,etda_operation_year,total_ops
125,"DustSquad, Golden Falcon",2014,[],0
156,Predator Panda,None Provided,[],0
157,Sabre Panda,None Provided,[],0
158,Singing Spider,None Provided,[],0
159,Solar Spider,None Provided,[],0
...,...,...,...,...
252,LockBit Gang,2019,"[2020, 2020, 2020, 2020, 2021, 2021, 2021, 202...",49
119,"Pinchy Spider, Gold Southfield",2018,"[2019, 2019, 2019, 2019, 2019, 2019, 2020, 202...",57
10,"Sofacy, APT 28, Fancy Bear, Sednit",2004,"[2011, 2013, 2014, 2014, 2015, 2015, 2015, 201...",63
0,"Lazarus Group, Hidden Cobra, Labyrinth Chollima",2007,"[2007, 2009, 2011, 2013, 2013, 2013, 2014, 201...",69
36,"Wizard Spider, Gold Blackburn",2014,"[2019, 2019, 2019, 2019, 2019, 2019, 2019, 201...",86

Count the number of operations in the same year as they are first seen

In [47]:
df = df.explode('etda_operation_year')

df['etda_operation_year'] = df['etda_operation_year'].where(df['etda_operation_year'] == df['etda_first_seen'],'')
df.loc[df['etda_operation_year'] != '']
df = df.groupby(['etda_name']).agg({'etda_name':'first','etda_first_seen':'first','total_ops':'first','etda_operation_year':'list'})
df.sort_values(by='etda_operation_year',ascending=False)

ValueError: 'etda_name' is both an index level and a column label, which is ambiguous.